version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - '.env'
    ports:
      - "30000:5000"
    container_name: govtech

  # mongodb:
  #   image: mongo:latest
  #   container_name: mongodb
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: 
  #     MONGO_INITDB_ROOT_PASSWORD: 
  #   volumes:
  #     - ./mongo-scripts:/docker-entrypoint-initdb.d/

